添加Github Action自动构建
isHarryh/Ark-Pets pull request #52
Opened 2023-11-27 15:22 UTC by half-nothing

1.添加Github Action自动构建功能
对于```core``` ```assert``` ```desktop```三个文件夹的提交将会触发自动构建
对于任何一个带有tag(eg: v2.3.2)的提交将会在自动构建后自动发布release
同时也可以在Action选项卡里吗进行手动构建
2.给README加了点图标

2023-12-03 01:41 UTC, isHarryh commented
> 1.添加Github Action自动构建功能
> 对于```core``` ```assert``` ```desktop```三个文件夹的提交将会触发自动构建

非常感谢你的 PR。关于远程仓库自动构建，先前确有考虑加入，但由于手动操作工作量不大，并未付诸实行。

另外，`assert` 目录名可能拼写有误，应为  `assets` 。

2023-12-10 01:07 UTC, isHarryh commented
2. `distExe` Task 要求开发机安装 InnoSetup，否则无法执行。
3. JDK 应为 17。

短期内不计划对所有格式的 Release 进行 Action 自动化，最多使用 Action进行 ComplieJava 等测试或 **只分发 Jar**。

2023-12-10 01:18 UTC, isHarryh requested changes

2023-12-10 01:18 UTC, isHarryh commented on .github/workflows/build.yml
> +      - 'assert/**'
Correct to: assets/**

2023-12-10 01:18 UTC, isHarryh commented on .github/workflows/build.yml
> +      - 'assert/**'
Correct to: assets/**

2023-12-10 01:18 UTC, isHarryh commented on .github/workflows/build.yml
> +      - name: Set up JDK 20
Correct to: 17

2023-12-10 01:18 UTC, isHarryh commented on .github/workflows/build.yml
> +        run: gradle clean distAll
Correct to: distZip

2023-12-10 01:18 UTC, isHarryh commented on .github/workflows/build.yml
> +      - name: Upload Exe
Delete this task node

2023-12-11 08:00 UTC, half-nothing commented on .github/workflows/build.yml
> +      - 'assert/**'
Corrected

2023-12-11 08:00 UTC, half-nothing commented on .github/workflows/build.yml
> +      - name: Set up JDK 20
Corrected

2023-12-11 08:38 UTC, half-nothing commented
> 2. `distExe` Task 要求开发机安装 InnoSetup，否则无法执行。
> 3. JDK 应为 17。
> 
> 短期内不计划对所有格式的 Release 进行 Action 自动化，最多使用 Action进行 ComplieJava 等测试或 **只分发 Jar**。
Github 的 Action 环境自带了Inno Setup 6，所以可以运行
![image](https://github.com/isHarryh/Ark-Pets/assets/50048293/e0a0f8c0-5493-4520-a615-2d59c39d664e)
但是由于 Github提供的windows环境是英文版本，所以exe安装包会出现乱码问题，此问题暂时无解

2023-12-16 09:47 UTC, isHarryh approved these changes
Okay

2023-12-16 09:50 UTC, merged

2023-12-16 14:07 UTC, isHarryh commented
Rewrote and force-pushed the merged commits into a rebased branch.